"use strict";

/**
 * Bangun HTML laporan ping server.
 * @param {Array<{serverName:string,targetIP:string,alive:boolean,min:number|null,max:number|null,avg:number|null,packetLoss:number|null}>} results
 */
function buildPingReportHTML(results) {
  const ok = (v) => (v === null || v === undefined || Number.isNaN(v)) ? '-' : String(v);
  const rows = results.map(r => `
    <tr>
      <td>${escapeHtml(r.serverName)}</td>
      <td>${escapeHtml(r.targetIP)}</td>
      <td>${r.alive ? '<span class="status status-up">UP</span>' : '<span class="status status-down">DOWN</span>'}</td>
      <td>${ok(r.min)}</td>
      <td>${ok(r.max)}</td>
      <td>${ok(r.avg)}</td>
      <td>${ok(r.packetLoss)}</td>
    </tr>
  `).join('');

  const now = new Date();
  const time = `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`;

  return `<!doctype html>
  <html lang="id">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Laporan Ping Server</title>
      <style>
        :root{ --bg:#ffffff; --text:#1e293b; --muted:#64748b; --up:#16a34a; --down:#dc2626; --border:#e2e8f0; }
        body{ margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu; color:var(--text); background:var(--bg); }
        .wrap{ padding:16px 20px; }
        .header{ display:flex; align-items:center; justify-content:space-between; margin-bottom:12px; }
        .title{ font-weight:700; font-size:18px; }
        .time{ font-size:12px; color:var(--muted); }
        table{ width:100%; border-collapse:collapse; font-size:12px; }
        th, td{ padding:8px 10px; border-bottom:1px solid var(--border); text-align:left; }
        th{ background:#f8fafc; font-weight:600; }
        .status{ padding:2px 8px; border-radius:999px; color:#fff; font-size:11px; font-weight:700; }
        .status-up{ background:var(--up); }
        .status-down{ background:var(--down); }
        .footer{ margin-top:10px; color:var(--muted); font-size:11px; }
      </style>
    </head>
    <body>
      <div class="wrap">
        <div class="header">
          <div class="title">Laporan Ping Server</div>
          <div class="time">${escapeHtml(time)}</div>
        </div>
        <table>
          <thead>
            <tr>
              <th>Nama Server</th>
              <th>IP</th>
              <th>Status</th>
              <th>Min (ms)</th>
              <th>Max (ms)</th>
              <th>Avg (ms)</th>
              <th>Loss (%)</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>
        <div class="footer">Generated by WA Bot</div>
      </div>
    </body>
  </html>`;
}

function escapeHtml(s) {
  return String(s)
    .replaceAll('&','&amp;')
    .replaceAll('<','&lt;')
    .replaceAll('>','&gt;')
    .replaceAll('"','&quot;')
    .replaceAll("'",'&#39;');
}

module.exports = { buildPingReportHTML };
